# Defines a GitHub Actions workflow named "Close stale issues and PRs" to automatically close inactive issues and pull requests.
name: "Close stale issues and PRs"

# Sets the workflow trigger mechanism, which is a scheduled trigger running daily at 1:30 AM.
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      # Utilizes the actions/stale@v8 action to process outdated issues and pull requests.
      - uses: actions/stale@v8
        with:
          # Messages and time settings for identifying and closing stale issues and PRs.
          stale-issue-message: "This issue is considered stale because it has been open for 30 days without activity. Please remove the stale label or comment, or it will be closed in 5 days."
          stale-pr-message: "This PR is considered stale because it has been open for 45 days without activity. Please remove the stale label or comment, or it will be closed in 10 days."
          close-issue-message: "This issue was closed due to inactivity for 5 days after being marked as stale."
          close-pr-message: "This PR was closed due to inactivity for 10 days after being marked as stale."
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10
